### PR TITLE
ProQuest export fixes

### LINKED ISSUE #737: Changes to ProQuest Export
- [x] generated zip files must start with "upload_"
- [x] attached xml file must be named "_DATA.xml"
- [x] change `<DISS_submission>` to `<DISS_submission publishing_option="0" embargo_code="0">` where Embargo codes are:
0 = no embargo
1 = 6 month embargo
2 = 1 year embargo
3 = 2 year embargo

- [x] Ask what we do for 6 year embargoes

- [x] If the page count cannot be determined, default to "1" instead of "unknown"
- [x] Add `<DISS_processing_code>F</DISS_processing_code>` assuming it is a doctoral submission. Add O if it is a masters submission.

- [x] Put supplemental files in their own directory: "any supplementary files added to the ZIP files to be in their own directory, named author_lastname_author_firstname_Media"

- [x] Send new sample to ProQuest and ask for feedback

- [x] ProQuest embargo support for embargoes longer than 2 years (see below)

- [x] accept date field must be in MM/DD/YYYY format

- [x] country field (in the author contact section) must be 2-letter abbreviation

- [x] Send another sample and get feedback from proquest

### PR DESCRIPTION
**Pull request by bess**
Exported package should be named as upload_*.zip
Exported XML file should be named as *_DATA.xml
Page number should default to 1 if page number cannot
be determined.
Add publishing_option and embargo_code to DISS_submission
Add DISS_processing_code
Put supplemental files in their own directory
Sample data rake task should run background jobs inline

Fixes #737

### CODE REVIEW

File: app/models/proquest_behaviors.rb [hunk 1]
```diff
@@ -10,12 +10,22 @@ module ProquestBehaviors
...
+      zip.file.open("#{upload_file_id}/#{xml_filename}", 'w') { |file| file.write(export_proquest_xml) }
+      # The primary thesis file goes in the main directory
+      primary_file_fs.each do |fs|
+        zip.file.open("#{upload_file_id}/#{fs.label}", "wb") do |saved_file|
+          open(fs.files.first.uri, "rb") do |read_file|
+            saved_file.write(read_file.read)
+          end
+        end
+      end
+      # Any supplemental files go into a subdirectory called lastname_firstname_Media
```
Comment (jenlindner) [inline app/models/proquest_behaviors.rb]: 👍

File: lib/tasks/sample_data.rake [hunk 2]
```diff
@@ -183,7 +184,7 @@ namespace :sample_data do
     puts "Exporting sample ProQuest package"
     etd = proquest_demo
     ProquestJob.perform_now(etd)
-    export_location = Rails.configuration.proquest_export_directory.join("#{etd.export_id}.zip").to_s
+    export_location = "#{etd.export_directory}/#{etd.upload_file_id}.zip"
```
Comment (jenlindner) [inline lib/tasks/sample_data.rake]: 👍
